# Generated by Django 5.2.5 on 2025-08-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=10)),
                ('cuatrimestre', models.CharField(choices=[('1', '1º Cuatr.'), ('2', '2º Cuatr.'), ('A', 'Anual'), ('V', 'Verano')], max_length=1)),
                ('nombre', models.CharField(max_length=160)),
                ('horas', models.PositiveIntegerField(default=0)),
                ('formato', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['profesorado', 'anio', 'cuatrimestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('plan_vigente', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteProfesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohorte', models.CharField(blank=True, max_length=20)),
                ('libreta', models.CharField(blank=True, max_length=50)),
                ('legajo', models.CharField(blank=True, max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academia_core.estudiante')),
                ('profesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academia_core.profesorado')),
            ],
            options={
                'unique_together': {('estudiante', 'profesorado')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REG', 'Regularidad'), ('FIN', 'Final')], max_length=3)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('condicion', models.CharField(max_length=20)),
                ('nota_num', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nota_texto', models.CharField(blank=True, max_length=40)),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('libro', models.CharField(blank=True, max_length=20)),
                ('disposicion_interna', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='academia_core.espaciocurricular')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='academia_core.estudianteprofesorado')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.AddField(
            model_name='espaciocurricular',
            name='profesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='academia_core.profesorado'),
        ),
        migrations.AlterUniqueTogether(
            name='espaciocurricular',
            unique_together={('profesorado', 'anio', 'cuatrimestre', 'nombre')},
        ),
    ]
