# Generated by Django 5.2.5 on 2025-08-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcionespacio",
            name="fecha_baja",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="inscripcionespacio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "BAJA"), ("fecha_baja__isnull", False)),
                    models.Q(("estado", "BAJA"), _negated=True),
                    _connector="OR",
                ),
                name="cursada_fecha_baja_si_baja",
            ),
        ),
    ]
