# Generated by Django 5.2.5 on 2025-08-10 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='espaciocurricular',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('vigente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('profesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='academia_core.profesorado')),
            ],
        ),
        migrations.AddField(
            model_name='espaciocurricular',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan al que pertenece (permite múltiples planes por profesorado).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='academia_core.planestudios'),
        ),
        migrations.AddConstraint(
            model_name='espaciocurricular',
            constraint=models.UniqueConstraint(fields=('profesorado', 'plan', 'anio', 'cuatrimestre', 'nombre'), name='uniq_espacio_por_prof_plan_anio_cuatri_nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='planestudios',
            unique_together={('profesorado', 'resolucion')},
        ),
    ]
