# Generated by Django 5.2.5 on 2025-08-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0002_inscripcionespacio_fecha_baja_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcionespacio",
            name="motivo_baja",
            field=models.TextField(blank=True, default=""),
        ),
    ]
