# Generated by Django 5.2.5 on 2025-08-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0002_alter_espaciocurricular_unique_together_planestudios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espaciocurricular',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='espaciocurricular',
            name='uniq_espacio_por_prof_plan_anio_cuatri_nombre',
        ),
        migrations.AlterField(
            model_name='espaciocurricular',
            name='cuatrimestre',
            field=models.CharField(choices=[('1', '1º Cuatr.'), ('2', '2º Cuatr.'), ('A', 'Anual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='espaciocurricular',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='academia_core.planestudios'),
        ),
        migrations.AddConstraint(
            model_name='espaciocurricular',
            constraint=models.UniqueConstraint(fields=('profesorado', 'plan', 'anio', 'cuatrimestre', 'nombre'), name='uniq_espacio_por_plan_y_anio_cuatri_nombre'),
        ),
    ]
