# Generated by Django 5.2.5 on 2025-08-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0003_alter_espaciocurricular_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espaciocurricular',
            options={'ordering': ['anio', 'cuatrimestre', 'nombre']},
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='curso_introductorio',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado'), ('En curso', 'En curso'), ('No aplica', 'No aplica')], max_length=20),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_cert_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_dni_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_folios_oficio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_fotos_carnet',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_incumbencias_titulo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_titulo_sec_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_titulo_superior_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='legajo_estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto')], default='Incompleto', max_length=12),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='promedio_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
