# Generated by Django 5.2.5 on 2025-08-11 02:42

import academia_core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0004_alter_espaciocurricular_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=academia_core.models.estudiante_foto_path),
        ),
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='doc_folios_oficio',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='doc_fotos_carnet',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
