# Generated by Django 5.2.5 on 2025-08-21 00:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0004_rename_fecha_a_fecha_inscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcionespacio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inscripcionespacio",
            name="fecha",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="inscripcionespacio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inscripcionespacio",
            name="fecha_inscripcion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
