# Generated by Django 5.2.5 on 2025-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0005_estudiante_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudios',
            name='resolucion_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesorado',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
