# Generated by Django 5.2.5 on 2025-08-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0006_planestudios_resolucion_slug_profesorado_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academia_core.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='academia_core.espaciocurricular')),
            ],
            options={
                'unique_together': {('docente', 'espacio')},
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='espacios',
            field=models.ManyToManyField(blank=True, related_name='docentes', through='academia_core.DocenteEspacio', to='academia_core.espaciocurricular'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('BEDEL', 'Bedelía'), ('TUTOR', 'Tutor'), ('SECRETARIA', 'Secretaría')], default='ESTUDIANTE', max_length=20)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='academia_core.docente')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='academia_core.estudiante')),
                ('profesorados_permitidos', models.ManyToManyField(blank=True, related_name='usuarios_habilitados', to='academia_core.profesorado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
