# Generated by Django 5.2.5 on 2025-08-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0007_docente_docenteespacio_docente_espacios_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciocurricular',
            name='libre_habilitado',
            field=models.BooleanField(default=False, help_text='Permite rendir en condición de Libre'),
        ),
        migrations.CreateModel(
            name='Correlatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSAR', 'Para cursar'), ('RENDIR', 'Para rendir')], max_length=10)),
                ('requisito', models.CharField(choices=[('REGULARIZADA', 'Regularizada'), ('APROBADA', 'Aprobada')], max_length=14)),
                ('requiere_todos_hasta_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_de', to='academia_core.espaciocurricular')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlatividades', to='academia_core.planestudios')),
                ('requiere_espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_requeridas', to='academia_core.espaciocurricular')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('requiere_espacio__isnull', False), ('requiere_todos_hasta_anio__isnull', True)), models.Q(('requiere_espacio__isnull', True), ('requiere_todos_hasta_anio__isnull', False)), _connector='OR'), name='correlatividad_requiere_algo'), models.UniqueConstraint(fields=('plan', 'espacio', 'tipo', 'requisito', 'requiere_espacio', 'requiere_todos_hasta_anio'), name='uniq_correlatividad_regla')],
            },
        ),
    ]
