# academia_core/migrations/0009_inscripcionespacio.py
# Generated by Django 5.2.5 on 2025-08-11 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0008_espaciocurricular_libre_habilitado_correlatividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscripcionEspacio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anio_academico", models.PositiveIntegerField(default=2025)),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("estado", models.CharField(
                    choices=[("EN_CURSO", "En curso"), ("BAJA", "Baja")],
                    default="EN_CURSO",
                    max_length=12,
                )),
                ("espacio", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="cursadas",
                    to="academia_core.espaciocurricular",
                )),
                ("inscripcion", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="cursadas",
                    to="academia_core.estudianteprofesorado",
                )),
            ],
            options={
                # Solo esta unicidad, sin constraints con JOIN
                "unique_together": {("inscripcion", "espacio", "anio_academico")},
            },
        ),
    ]
