# Generated by Django 5.2.5 on 2025-08-12 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0009_inscripcionespacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_cache', models.CharField(blank=True, max_length=20)),
                ('accion', models.CharField(choices=[('MOV_ALTA', 'Carga de movimiento'), ('INSC_PROF', 'Inscripción a profesorado'), ('INSC_ESP', 'Inscripción a materia'), ('LOGIN', 'Ingreso'), ('LOGOUT', 'Salida')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
