# Generated by Django 5.2.5 on 2025-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0010_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='legajo_entregado',
            field=models.BooleanField(default=False),
        ),
    ]
