# Generated by Django 5.2.5 on 2025-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0012_remove_inscripcionespacio_cursada_mismo_profesorado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcionespacio',
            options={'ordering': ['-anio_academico', 'espacio__anio', 'espacio__cuatrimestre', 'espacio__nombre']},
        ),
        migrations.AlterField(
            model_name='inscripcionespacio',
            name='anio_academico',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inscripcionespacio',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'EN_CURSO'), ('BAJA', 'BAJA')], default='EN_CURSO', max_length=10),
        ),
    ]
