# Generated by Django 5.2.5 on 2025-08-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0013_alter_inscripcionespacio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='adeuda_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='adeuda_materias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='colegio',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
