# Generated by Django 5.2.5 on 2025-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0014_estudianteprofesorado_adeuda_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='nota_compromiso',
            field=models.BooleanField(default=False),
        ),
    ]
