# Generated by Django 5.2.5 on 2025-08-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0018_remove_espaciocurricular_uniq_espacio_por_plan_y_anio_cuatri_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('AUSENTE', 'Ausente')], default='INSCRIPTO', max_length=12)),
                ('nota_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ausente', models.BooleanField(default=False)),
                ('ausencia_justificada', models.BooleanField(default=False)),
                ('inscripcion_cursada', models.ForeignKey(help_text='Cursada regular vigente en base a la cual el estudiante se presenta.', on_delete=django.db.models.deletion.CASCADE, related_name='finales', to='academia_core.inscripcionespacio')),
            ],
            options={
                'verbose_name': 'Inscripción a Mesa Final',
                'verbose_name_plural': 'Inscripciones a Mesas Finales',
                'ordering': ['-creado'],
                'unique_together': {('inscripcion_cursada', 'fecha_examen')},
            },
        ),
    ]
