# Generated by Django 5.2.5 on 2025-08-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0019_inscripcionfinal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionfinal',
            old_name='nota_num',
            new_name='nota_final',
        ),
        migrations.AlterField(
            model_name='inscripcionfinal',
            name='inscripcion_cursada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finales', to='academia_core.inscripcionespacio'),
        ),
    ]
