# Generated by Django 5.2.5 on 2025-08-16 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0020_rename_nota_num_inscripcionfinal_nota_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionfinal',
            name='nota_final',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
