# Generated by Django 5.2.5 on 2025-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0021_alter_inscripcionfinal_nota_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='doc_folios_oficio',
            field=models.BooleanField(default=False, verbose_name='Folios oficio'),
        ),
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='doc_fotos_carnet',
            field=models.BooleanField(default=False, verbose_name='Fotos carnet'),
        ),
    ]
