# Generated by Django 5.2.5 on 2025-08-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0025_condicion_espaciocondicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicion',
            name='orden',
        ),
    ]
