# Generated by Django 5.2.5 on 2025-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0026_remove_condicion_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudianteprofesorado',
            name='doc_incumbencias_titulo',
        ),
        migrations.RemoveField(
            model_name='estudianteprofesorado',
            name='doc_titulo_superior_legalizado',
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='condicion_admin',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CONDICIONAL', 'Condicional')], default='CONDICIONAL', max_length=20, verbose_name='Condición administrativa'),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_incumbencias',
            field=models.BooleanField(default=False, verbose_name='Incumbencias presentadas'),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='doc_titulo_terciario_legalizado',
            field=models.BooleanField(default=False, verbose_name='Doc título terciario/universitario legalizado'),
        ),
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='legajo_estado',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto')], default='INCOMPLETO', max_length=20, verbose_name='Legajo estado'),
        ),
        migrations.AlterField(
            model_name='estudianteprofesorado',
            name='libreta',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Libreta'),
        ),
    ]
