# Generated by Django 5.2.5 on 2025-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0027_remove_estudianteprofesorado_doc_incumbencias_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='libreta_entregada',
            field=models.BooleanField(default=False, verbose_name='Libreta entregada'),
        ),
    ]
