# Generated by Django 5.2.5 on 2025-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0028_estudianteprofesorado_libreta_entregada'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='institucion_origen',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Escuela / Institución'),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='materias_adeudadas',
            field=models.TextField(blank=True, default='', verbose_name='Materias adeudadas'),
        ),
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='titulo_en_tramite',
            field=models.BooleanField(default=False, verbose_name='Título en trámite'),
        ),
    ]
